# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "Setup Environment"
description: "Bootstraps a Pure Devbox environment with tiered caching"

inputs:
  devbox-cache:
    description: "Enable Devbox Nix store caching"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - id: install-devbox
      name: Install Devbox
      uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 # v0.15.0
      with:
        enable-cache: ${{ inputs.devbox-cache }}

    - id: cache-npm
      name: Cache NPM Global
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json', 'docs/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - id: cache-jest
      name: Cache Jest Transformations
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: .jest-cache
        key: ${{ runner.os }}-jest-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-jest-

    - id: cache-docs
      name: Cache Docusaurus Metadata
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: docs/.docusaurus
        key: ${{ runner.os }}-docs-${{ hashFiles('docs/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-docs-

    - id: setup
      name: Setup dependencies
      shell: bash
      run: npm run all:setup
