name: Maintenance Runner
on:
  workflow_dispatch:
    inputs:
      script:
        description: "npm script to run"
        required: true
        type: choice
        options:
          - "all:audit-security"
          - "all:build"
          - "all:ci"
          - "all:clean"
          - "all:deploy"
          - "all:format"
          - "all:lint"
          - "all:locks-clean"
          - "all:maintenance"
          - "all:packages-outdated"
          - "all:packages-update"
          - "all:pre-commit"
          - "all:pre-commit:fast"
          - "all:pre-push"
          - "all:push"
          - "all:rebuild"
          - "all:rebuild:fast"
          - "all:redeploy"
          - "all:reinstall"
          - "all:release-dry-run"
          - "all:repush"
          - "all:setup"
          - "all:test"
          - "all:update"
env:
  ACT: false
  DEVBOX_NO_LOG_PROGRESS: 1
  DEVBOX_QUIET: 1
  NIX_CONFIG: "quiet = true"
permissions:
  contents: read
jobs:
  run-maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
      - name: Run script
        run: devbox --quiet run npm run ${{ github.event.inputs.script }}
