name: snyk-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Renovate will update this to SHA
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24.x"
          cache: "npm"
      - name: Install dependencies (lib)
        run: npm run setup:lib
      - name: Snyk Test (lib)
        if: env.ACT != 'true'
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
      - name: Install dependencies (docs)
        run: npm run setup:docs
      - name: Snyk Test (docs)
        if: env.ACT != 'true'
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --file=docs/package.json
