name: snyk-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ACT: false
  DEVBOX_QUIET: 1

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
      - name: Snyk Test (lib)
        if: env.ACT != 'true'
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
      - name: Snyk Test (docs)
        if: env.ACT != 'true'
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --file=docs/package.json
